image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp dist/Evan.Plaice-Full.Stack.Dev.html public/index.html
    - cp dist/Evan.Plaice-Full.Stack.Dev.html public/Evan.Plaice-Full.Stack.Dev.html
    - cp dist/Evan.Plaice-Full.Stack.Dev.pdf public/Evan.Plaice-Full.Stack.Dev.pdf
  artifacts:
    paths:
    - public
  only:
  - master
